module.exports = {
    uk: {
        name: '🇬🇧 United Kingdom',
        value: 'GB',
        locale: 'en',
        currency: 'GBP',
        shipping: {},
    },
    us: {
        name: '🇺🇸 United States',
        value: 'US',
        locale: 'en',
        currency: 'USD',
        shipping: {},
    },
    at: {
        name: '🇦🇹 Austria',
        value: 'AT',
        locale: 'en',
        currency: 'EUR',
        shipping: {},
    },
    be: {
        name: '🇧🇪 Belgium',
        value: 'BE',
        locale: 'en',
        currency: 'EUR',
        shipping: {},
    },
    cn: {
        name: '🇨🇳 China',
        value: 'CN',
        locale: 'zh',
        currency: 'CNY',
        shipping: {},
    },
    de: {
        name: '🇩🇪 Germany',
        value: 'DE',
        locale: 'de',
        currency: 'EUR',
        shipping: {},
    },
    fr: {
        name: '🇫🇷 France',
        value: 'FR',
        locale: 'fr',
        currency: 'EUR',
        shipping: {
            address: {
                city: "Berlin",
                zip: "10101",
                country: "DE"
            }
        },
    },
    it: {
        name: '🇮🇹 Italy',
        value: 'IT',
        locale: 'it',
        currency: 'EUR',
        shipping: {},
    },
    kw: {
        name: '🇰🇼 Kuwait',
        value: 'KW',
        locale: 'it',
        currency: 'KWD',
        shipping: {},
    },
    nl: {
        name: '🇳🇱 Netherlands',
        value: 'NL',
        locale: 'itnl',
        currency: 'EUR',
        shipping: {},
    },
    pt: {
        name: '🇵🇹 Portugal',
        value: 'PT',
        locale: 'pt',
        currency: 'EUR',
        shipping: {},
    },
    pl: {
        name: '🇵🇱 Poland',
        value: 'PL',
        locale: 'en',
        currency: 'EUR',
        shipping: {},
    },
    sa: {
        name: '🇸🇦 Saudi Arabia',
        value: 'AR',
        locale: 'ar',
        currency: 'SAR',
        shipping: {},
    },
    es: {
        name: '🇪🇸 Spain',
        value: 'ES',
        locale: 'es',
        currency: 'EUR',
        shipping: {},
    },
    vi: {
        name: '🇻🇳 Vietnam',
        value: 'VI',
        locale: 'vi',
        currency: 'VND',
        shipping: {},
    },
}
